// lifecycle-data.js — Default data for Document Lifecycle tool

const DEFAULT_PHASES = {
  intake:       { label: '00 Intake',       color: '#c4a882' },
  discovery:    { label: '01 Discovery',    color: '#7ea8c4' },
  solution:     { label: '02 Solution',     color: '#68b2a0' },
  delivery:     { label: '03 Delivery',     color: '#7b91d4' },
  governance:   { label: '04 Governance',   color: '#e0a060' },
  architecture: { label: '05 Architecture', color: '#b088cc' },
};

const DEFAULT_ROLES = [
  { key: 'executive-sponsor',  title: 'Executive Sponsor',  name: '' },
  { key: 'product-owner',      title: 'Product Owner',      name: '' },
  { key: 'business-analyst',   title: 'Business Analyst',   name: '' },
  { key: 'tech-lead',          title: 'Tech Lead',          name: '' },
  { key: 'solution-architect', title: 'Solution Architect', name: '' },
  { key: 'developer',          title: 'Developer',          name: '' },
  { key: 'senior-developer',   title: 'Senior Developer',   name: '' },
  { key: 'tester',             title: 'Tester',             name: '' },
  { key: 'qa-engineer',        title: 'QA Engineer',        name: '' },
  { key: 'scrum-master',       title: 'Scrum Master',       name: '' },
  { key: 'stakeholder',        title: 'Stakeholder',        name: '' },
  { key: 'end-user',           title: 'End User',           name: '' },
  { key: 'security-officer',   title: 'Security Officer',   name: '' },
  { key: 'full-team',          title: 'Full Team',          name: '' },
];

const DEFAULT_DOCUMENTS = [

// ══ INTAKE ════════════════════════════════════════════════════════════════

{
  phase:'intake', key:'org-constitution',
  title:'Org Constitution', sub:'Organisation-wide standards (baseline)',
  path:'_org/constitution.md',
  owner:'Tech Lead',
  reviewers:['Solution Architect','Security Officer'],
  signoff:'Solution Architect',
  lifecycle:'Versioned — major review yearly, minor updates anytime',
  trigger:'New organisation standards or yearly review cycle',
  doel:'Establish the baseline coding, security, and process standards that every project must follow or explicitly override.',
  inputs:['Industry standards (OWASP, ISO 27001)','Lessons from past projects','Architecture board decisions'],
  outputs:['Baseline for all project constitutions','System prompt context for AI agents across all projects'],
  flow:[
    {name:'Yearly Review',sub:'Or triggered by incident',type:'trigger'},
    {name:'Draft Update',sub:'Principal Architect',type:'step'},
    {name:'Review Board',sub:'TL + Security + Architect',type:'step'},
    {name:'Sign-off',sub:'Principal Architect',type:'signoff'},
    {name:'Published',sub:'All projects inherit',type:'output'},
  ],
  note:'Project constitutions can override specific sections by explicitly declaring an override. Silent conflicts are not allowed.',
  refs:[{dir:'→',key:'project-constitution'}],
  creation:[
    {name:'Review industry standards',method:'Document analysis',tools:'OWASP, ISO docs, NIST',ai:true},
    {name:'Workshop with board',method:'Facilitated discussion',tools:'Miro, video call',ai:false},
    {name:'Draft document',method:'Structured writing',tools:'Markdown, Claude',ai:true},
    {name:'Annual review cycle',method:'Diff against previous version',tools:'Git, Claude',ai:true},
  ],
  template:'# Org Constitution\n\nVersion: [X.Y] | Effective: [date]\n\n## Purpose\nBaseline standards for all [Org] software projects.\n\n## Coding Standards\n- Language versions:\n- Linting:\n- Naming conventions:\n- Commit format: Conventional Commits\n\n## Security Baseline\n- Auth standard:\n- Secrets management:\n- Dependency scanning: (required)\n- Data classification levels:\n\n## Quality Gates\n| Gate | Requirement |\n|---|---|\n| Unit test coverage | min. X% |\n| Linting | zero errors |\n| Security scan | zero high/critical |\n\n## Default Tooling\n| Category | Tool |\n|---|---|\n| Version control | |\n| CI/CD | |\n| Monitoring | |\n\n## AI Agent Guidance\n- Language: English\n- Documentation: inline only where non-obvious\n- Never commit secrets\n- Always validate external input\n',
  aiTasks:[
    {name:'Standards Completeness Checker',persona:'Enterprise Architect',objective:'Verify the org constitution covers all mandatory governance areas.',prompt:'You are an Enterprise Architect. Review this org constitution for completeness: coding standards, security baseline (OWASP alignment), data protection, quality gates, tooling defaults, AI guidance. Flag missing sections with suggested content.'},
    {name:'Security Baseline Reviewer',persona:'Security Engineer',objective:'Assess the security section against OWASP SAMM Level 1.',prompt:'You are a Security Engineer. Review the security section against OWASP SAMM Level 1. Identify missing practices, outdated recommendations, and practices too vague to enforce. Output a gap analysis with recommended additions.'},
  ],
},

{
  phase:'intake', key:'project-constitution',
  title:'Project Constitution', sub:'Project-level standards and overrides',
  path:'[project]/constitution.md',
  owner:'Tech Lead',
  reviewers:['Product Owner','Business Analyst'],
  signoff:'Executive Sponsor',
  lifecycle:'One-time — versioned when major tech decisions change',
  trigger:'Project start or adoption of a new tech stack',
  doel:'Define project-specific standards (tech stack, conventions, tooling) that extend or override the org constitution.',
  inputs:['Org Constitution (baseline)','Client tech constraints','Team skills and preferences'],
  outputs:['Single source of truth for project conventions','AI agent system context','Developer onboarding baseline'],
  flow:[
    {name:'Project Start',sub:'Tech Lead initiates',type:'trigger'},
    {name:'Draft',sub:'TL + BA + PO',type:'step'},
    {name:'Org Alignment',sub:'Check against org constitution',type:'step'},
    {name:'Sign-off',sub:'Executive Sponsor',type:'signoff'},
    {name:'Active',sub:'Used throughout project lifetime',type:'output'},
  ],
  note:'AI agents should receive this document as system context. Project overrides must explicitly reference the org constitution section they override.',
  refs:[{dir:'←',key:'org-constitution'}],
  creation:[
    {name:'Define tech requirements',method:'Architecture workshop',tools:'Miro, whiteboard',ai:false},
    {name:'Check org constitution',method:'Gap analysis',tools:'Claude, Markdown diff',ai:true},
    {name:'Draft document',method:'Structured writing',tools:'Markdown, Claude',ai:true},
    {name:'Get sign-off',method:'Review meeting',tools:'Video call, Confluence',ai:false},
  ],
  template:'# Project Constitution: [Project Name]\n\nVersion: 1.0 | Date: [date]\nOrg Constitution: v[X.Y]\n\n## Tech Stack\n| Layer | Technology | Version |\n|---|---|---|\n| Frontend | | |\n| Backend | | |\n| Database | | |\n| Cloud | | |\n\n## Project Overrides\n> These sections override the Org Constitution. Reference section by name.\n\n## Coding Conventions\n- Naming:\n- Folder structure:\n- Branching strategy:\n\n## Testing Requirements\n- Unit: min. X% coverage\n- Integration:\n- E2E:\n\n## Security Requirements\n- Auth method:\n- Data classification:\n- Compliance:\n\n## AI Guidance\n- Language: English\n- Commit format:\n- Documentation style:\n',
  aiTasks:[
    {name:'Stack Validator',persona:'Solution Architect',objective:'Validate tech stack consistency and flag EOL versions or missing layers.',prompt:'You are a Solution Architect. Review this project constitution: (1) Are technology choices compatible? (2) Are any versions EOL or approaching EOL? (3) Are monitoring, CI/CD, and feature flags covered? (4) Does the stack match team skills? Output a risk table per technology choice.'},
    {name:'Org Alignment Checker',persona:'Enterprise Architect',objective:'Identify silent conflicts between project and org constitution.',prompt:'You are an Enterprise Architect. Compare this project constitution to the org constitution. Classify each section as: aligned / documented override / silent conflict / missing. Silent conflicts are highest priority — flag them explicitly.'},
  ],
},

{
  phase:'intake', key:'prd',
  title:'PRD', sub:'Product Requirements Document',
  path:'[project]/00_intake/prd.md',
  owner:'Product Owner',
  reviewers:['Executive Sponsor','Tech Lead'],
  signoff:'Executive Sponsor',
  lifecycle:'One-time — archived after kickoff',
  trigger:'Decision to build a new product or major feature',
  doel:'Formally capture the initiative, scope, and business objective as the starting point for discovery.',
  inputs:['Strategic goals from executive sponsor','Market research or customer feedback','Budget proposal'],
  outputs:['Approved initiative framework','Scope + out-of-scope defined','Discovery phase started'],
  flow:[
    {name:'Business Need',sub:'Sponsor identifies problem',type:'trigger'},
    {name:'Draft PRD',sub:'Product Owner writes',type:'step'},
    {name:'Review',sub:'Tech Lead + Sponsor',type:'step'},
    {name:'Sign-off',sub:'Executive Sponsor',type:'signoff'},
    {name:'Discovery starts',sub:'PRD archived',type:'output'},
  ],
  note:'The PRD is an entry gate, not a living document. After sign-off, epics and stories become the source of truth.',
  refs:[{dir:'→',key:'stakeholders'},{dir:'→',key:'pijnpunten'}],
  creation:[
    {name:'Understand business need',method:'Executive interviews',tools:'Zoom, Calendly',ai:false},
    {name:'Define scope',method:'MoSCoW workshop',tools:'Miro, Notion',ai:false},
    {name:'Draft PRD',method:'Structured writing',tools:'Claude, Notion',ai:true},
    {name:'Review with stakeholders',method:'Presentation + feedback',tools:'Slides, Confluence',ai:false},
  ],
  template:'# Product Requirements Document\n\n## Problem Statement\n\n## Target Users\n\n## Goals & Success Metrics\n| Metric | Baseline | Target |\n|---|---|---|\n\n## Scope\n### In Scope\n\n### Out of Scope\n\n## Assumptions & Constraints\n\n## Stakeholders\n\n## Budget Indication\n\n## Timeline\n',
  aiTasks:[
    {name:'Scope Validator',persona:'Senior Product Manager',objective:'Validate PRD completeness and flag scope creep risks.',prompt:'You are a Senior Product Manager. Review this PRD: (1) Is the problem statement specific and measurable? (2) Are success metrics SMART? (3) Is out-of-scope explicit? (4) Are assumptions documented? Output PASS/WARN/FAIL per section with improvements.'},
    {name:'Stakeholder Impact Analyst',persona:'Change Manager',objective:'Identify affected stakeholder groups and flag adoption risks.',prompt:'You are a Change Manager. Identify all stakeholder groups impacted by this PRD. For each: impact level (H/M/L), likely concerns, and recommended engagement strategy. Flag any group not mentioned but who should be involved.'},
  ],
},

{
  phase:'intake', key:'stakeholders',
  title:'Stakeholder Map', sub:'Who is involved and why',
  path:'[project]/00_intake/stakeholders.md',
  owner:'Business Analyst',
  reviewers:['Product Owner'],
  signoff:'',
  lifecycle:'Living — updated when new stakeholders are identified',
  trigger:'Project start or new stakeholder identified',
  doel:'Provide clarity on who has which interests so that communication and reviews are correctly targeted.',
  inputs:['Executive sponsor conversations','Organisational chart','PRD (initial version)'],
  outputs:['Stakeholder list with interests','Basis for interview planning in discovery'],
  flow:[
    {name:'Kickoff Meeting',sub:'First stakeholders mapped',type:'trigger'},
    {name:'Interviews',sub:'Business Analyst',type:'step'},
    {name:'Document',sub:'BA writes overview',type:'step'},
    {name:'Review PO',sub:'Informal sign-off',type:'step'},
    {name:'Living Doc',sub:'Updated as needed',type:'output'},
  ],
  note:'',
  refs:[{dir:'←',key:'prd'}],
  creation:[
    {name:'Identify stakeholders',method:'Org chart analysis + snowball',tools:'LinkedIn, Miro',ai:true},
    {name:'Conduct stakeholder interviews',method:'1-on-1 interviews',tools:'Zoom, Calendly',ai:false},
    {name:'Map interests and influence',method:'Power-interest grid',tools:'Miro',ai:true},
    {name:'Document RACI',method:'RACI matrix',tools:'Spreadsheet, Claude',ai:true},
  ],
  template:'# Stakeholder Map\n\n## Stakeholders\n| Name | Role | Interest | Influence | Availability |\n|---|---|---|---|---|\n\n## Power-Interest Grid\n```\nHigh power │ Keep satisfied  │ Manage closely\n           │                 │\n Low power │ Monitor (low)   │ Keep informed\n           ├─────────────────┴──────────────\n           Low interest       High interest\n```\n\n## RACI Summary\n| Deliverable | Responsible | Accountable | Consulted | Informed |\n|---|---|---|---|---|\n\n## Communication Plan\n| Stakeholder | Frequency | Channel | Owner |\n|---|---|---|---|\n',
  aiTasks:[
    {name:'Interview Planner',persona:'Senior Business Analyst',objective:'Generate tailored interview questions per stakeholder group.',prompt:'You are a Senior Business Analyst. Based on this stakeholder map, generate 5-8 targeted interview questions per stakeholder group. Uncover: unstated requirements, constraints, political sensitivities, success criteria. Format as a table: Stakeholder Group | Questions.'},
    {name:'RACI Generator',persona:'Project Manager',objective:'Generate a RACI matrix for the key project deliverables.',prompt:'You are a Project Manager. Based on this stakeholder map, generate a RACI matrix for the main project phases and deliverables. Flag roles with unclear accountability.'},
  ],
},

// ══ DISCOVERY ═════════════════════════════════════════════════════════════

{
  phase:'discovery', key:'as-is',
  title:'As-Is Process', sub:'Current state before digitalisation',
  path:'[project]/01_discovery/as-is-process.md',
  owner:'Business Analyst',
  reviewers:['End User','Stakeholder'],
  signoff:'',
  lifecycle:'One-time — reference for to-be comparison',
  trigger:'Start of discovery phase',
  doel:'Document the current way of working as the baseline for identifying pain points and improvement opportunities.',
  inputs:['On-site observations','Staff interviews','Stakeholder map'],
  outputs:['Visual process diagram of current state','Input for pain points analysis'],
  flow:[
    {name:'Observation',sub:'BA on-site',type:'trigger'},
    {name:'Interviews',sub:'Staff & end users',type:'step'},
    {name:'Modelling',sub:'BA writes as-is',type:'step'},
    {name:'Validation',sub:'Staff confirms accuracy',type:'step'},
    {name:'Validated Doc',sub:'Input for pain points',type:'output'},
  ],
  note:'',
  refs:[{dir:'→',key:'pijnpunten'}],
  creation:[
    {name:'On-site observation',method:'Shadowing / fly-on-the-wall',tools:'Notebook, camera',ai:false},
    {name:'Staff interviews',method:'Semi-structured interviews',tools:'Zoom, Miro',ai:false},
    {name:'Model the process',method:'BPMN / swimlane diagram',tools:'Miro, draw.io, Claude',ai:true},
    {name:'Validate with staff',method:'Walkthrough session',tools:'Miro, screen share',ai:false},
  ],
  template:'# As-Is Process: [Process Name]\n\n## Overview\n\n## Process Steps\n| Step | Actor | Input | Output | Tool / System |\n|---|---|---|---|---|\n| 1 | | | | |\n\n## Roles Involved\n\n## Systems & Tools Used\n\n## Process Diagram (Mermaid)\n```mermaid\nflowchart LR\n  A[Start] --> B[Step 1]\n  B --> C[End]\n```\n\n## Known Issues\n\n## Open Questions\n',
  aiTasks:[
    {name:'Process Gap Analyst',persona:'Business Process Consultant',objective:'Identify inefficiencies, bottlenecks, and manual workarounds.',prompt:'You are a Business Process Consultant. Review this as-is process: (1) bottlenecks, (2) manual steps to automate, (3) handoff points with high error risk, (4) undocumented exception paths. Output a prioritised gap list with impact H/M/L.'},
    {name:'Quick Win Identifier',persona:'Lean Process Expert',objective:'Surface low-effort improvements deliverable before the full digital solution.',prompt:'You are a Lean expert. Identify 3-5 quick wins achievable without a full digital solution (process changes, better use of existing tools). For each: effort (low/medium) and expected impact.'},
  ],
},

{
  phase:'discovery', key:'pijnpunten',
  title:'Pain Points', sub:'Structured problem analysis',
  path:'[project]/01_discovery/pain-points.md',
  owner:'Business Analyst',
  reviewers:['Product Owner','Executive Sponsor'],
  signoff:'Product Owner',
  lifecycle:'One-time — input for epic prioritisation',
  trigger:'As-is process validated',
  doel:'Prioritise pain points so that the right problems are in scope for the solution phase.',
  inputs:['As-is process description','Interviews and observations','Customer feedback (if available)'],
  outputs:['Prioritised pain point list','Basis for epic scope','KPI targets per pain point'],
  flow:[
    {name:'As-Is Complete',sub:'Trigger',type:'trigger'},
    {name:'Analysis',sub:'BA clusters pain points',type:'step'},
    {name:'Prioritisation',sub:'Workshop with PO',type:'step'},
    {name:'Sign-off PO',sub:'Scope confirmed',type:'signoff'},
    {name:'Input for Epics',sub:'Discovery closed',type:'output'},
  ],
  note:'Sign-off by the PO determines which pain points are in scope for V1.',
  refs:[{dir:'←',key:'as-is'},{dir:'→',key:'epic'}],
  creation:[
    {name:'Cluster raw observations',method:'Affinity mapping',tools:'Miro, sticky notes',ai:true},
    {name:'Root cause analysis',method:'5-Whys per pain point',tools:'Miro, Claude',ai:true},
    {name:'Prioritisation workshop',method:'Impact/effort matrix',tools:'Miro, Jira',ai:false},
    {name:'Document and sign off',method:'Structured writing',tools:'Confluence, Claude',ai:true},
  ],
  template:'# Pain Points\n\n## Summary\n\n## Pain Points\n\n### [Pain Point Name]\n- **Impact**: High / Medium / Low\n- **Frequency**: Daily / Weekly / Occasionally\n- **Description**:\n- **Root Cause** (5-Whys):\n- **KPI Target**:\n\n## Prioritisation Matrix\n| Pain Point | Impact | Effort | Priority |\n|---|---|---|---|\n\n## V1 Scope Decision\n### In Scope for V1\n\n### Deferred to V2+\n',
  aiTasks:[
    {name:'Root Cause Analyst',persona:'Business Analyst',objective:'Identify root causes vs. symptoms for each pain point.',prompt:'You are a BA skilled in root cause analysis. For each pain point, apply 5-Whys. Distinguish symptoms from root causes. Flag where the stated cause appears to be a symptom. Output: Pain Point | Symptom | Root Cause | Confidence.'},
    {name:'Priority Matrix Advisor',persona:'Product Owner',objective:'Score pain points by business impact and effort.',prompt:'You are a Product Owner. Score each pain point 1-5 on impact and effort. Calculate priority (impact/effort). Suggest a V1 scope maximising value within a realistic effort budget. Output as a prioritisation matrix.'},
  ],
},

{
  phase:'discovery', key:'persona',
  title:'User Persona', sub:'Primary end user profile',
  path:'[project]/01_discovery/persona-primary.md',
  owner:'Business Analyst',
  reviewers:['Product Owner'],
  signoff:'',
  lifecycle:'One-time — reference throughout the project',
  trigger:'User interviews completed',
  doel:'Create a shared picture of the primary user so UX decisions are consistent and user-centred.',
  inputs:['User interviews (min. 3)','On-site observations'],
  outputs:['Persona document','Reference for UX decisions in solution phase'],
  flow:[
    {name:'Interviews',sub:'Min. 3 end users',type:'trigger'},
    {name:'Synthesis',sub:'BA builds persona',type:'step'},
    {name:'PO Review',sub:'Informal',type:'step'},
    {name:'Published',sub:'Team reference',type:'output'},
  ],
  note:'',
  refs:[],
  creation:[
    {name:'User interviews',method:'Semi-structured, contextual inquiry',tools:'Zoom, Calendly, recording (with consent)',ai:false},
    {name:'Synthesise patterns',method:'Affinity mapping, empathy mapping',tools:'Miro, FigJam',ai:true},
    {name:'Write persona',method:'Narrative + data synthesis',tools:'Figma, Claude, Notion',ai:true},
    {name:'Validate with team',method:'Presentation',tools:'Slides, Miro',ai:false},
  ],
  template:'# Persona: [Name]\n\n## Profile\n- **Role**:\n- **Age range**:\n- **Tech comfort**: Low / Medium / High\n- **Context**: Where and how they work\n\n## Goals\n1.\n2.\n\n## Frustrations\n1.\n2.\n\n## A Day in the Life\n\n## Quote\n> "[typical thing this person would say]"\n\n## What success looks like\n',
  aiTasks:[
    {name:'Interview Guide Creator',persona:'UX Researcher',objective:'Generate a structured interview guide to uncover user behaviours and frustrations.',prompt:'You are a UX Researcher. Create a semi-structured interview guide for this persona. Include: warm-up, current behaviour & workarounds, frustration probes, goals/motivations, closing questions about ideal solutions. 3-4 questions per section with interviewer tips.'},
    {name:'Journey Mapper',persona:'UX Designer',objective:'Map the user journey to identify key touchpoints and emotional highs/lows.',prompt:'You are a UX Designer. Based on this persona, create a user journey map for their primary workflow: stages, actions, thoughts/feelings, pain points, opportunities. Highlight the 2-3 moments most important for UX investment. Format as a markdown table.'},
  ],
},

// ══ SOLUTION ══════════════════════════════════════════════════════════════

{
  phase:'solution', key:'epic',
  title:'Epic', sub:'Overarching goal of an initiative',
  path:'[project]/02_solution/epic-[name]/epic.md',
  owner:'Product Owner',
  reviewers:['Business Analyst','Tech Lead','Executive Sponsor'],
  signoff:'Executive Sponsor',
  lifecycle:'Living — updated on scope changes',
  trigger:'Pain points prioritised and approved',
  doel:'Define a deliverable block of business value that enables traceability and budget control.',
  inputs:['Approved pain points','PRD (scope)','User persona'],
  outputs:['Business outcome with KPIs','Scope definition','Basis for feature decomposition'],
  flow:[
    {name:'Pain Points OK',sub:'Trigger',type:'trigger'},
    {name:'Draft Epic',sub:'Product Owner',type:'step'},
    {name:'Review',sub:'BA + Tech Lead',type:'step'},
    {name:'Sign-off',sub:'Executive Sponsor',type:'signoff'},
    {name:'Features Start',sub:'Epic is living doc',type:'output'},
  ],
  note:'Sign-off is formal when the epic has budget impact. For smaller initiatives, informal PO agreement suffices.',
  refs:[{dir:'←',key:'pijnpunten'},{dir:'→',key:'domain'}],
  creation:[
    {name:'Business outcome workshop',method:'Value proposition canvas',tools:'Miro, Jira',ai:false},
    {name:'Define KPIs',method:'OKR workshop',tools:'Spreadsheet, Claude',ai:true},
    {name:'Scope definition',method:'MoSCoW with PO + BA',tools:'Miro, Confluence',ai:false},
    {name:'Write epic',method:'Structured writing',tools:'Claude, Jira, Confluence',ai:true},
  ],
  template:'# Epic: [Name]\n\n## Business Outcome\n\n## Problem Statement\n\n## Target Users\n\n## Success Metrics (KPIs)\n| Metric | Baseline | Target | Measurement |\n|---|---|---|---|\n\n## Scope\n### In Scope\n\n### Out of Scope\n\n## Features\n| Feature | Priority | Status |\n|---|---|---|\n\n## Assumptions\n\n## Dependencies\n\n## Open Questions\n',
  aiTasks:[
    {name:'Business Value Validator',persona:'Product Owner',objective:'Validate the epic has a clear, measurable outcome with realistic KPIs.',prompt:'You are a Product Owner. Review this epic: (1) Is business outcome measurable? (2) Are KPIs SMART? (3) Is scope realistic? (4) Are dependencies identified? Output PASS/WARN/FAIL per criterion.'},
    {name:'Feature Decomposer',persona:'Senior Business Analyst',objective:'Break the epic into logical features with clear boundaries.',prompt:'You are a Senior BA. Suggest a feature breakdown: (1) full scope coverage, (2) clear boundaries, (3) independently deliverable, (4) logically sequenced. For each: one-sentence description and inter-feature dependencies.'},
  ],
},

{
  phase:'solution', key:'feature',
  title:'Feature', sub:'Scoped piece of functionality within an epic',
  path:'[project]/02_solution/epic-[name]/feature-[name]/feature.md',
  owner:'Business Analyst',
  reviewers:['Product Owner','Tech Lead'],
  signoff:'Product Owner',
  lifecycle:'Living — updated on refinement or scope changes',
  trigger:'Epic approved and started',
  doel:'Document behaviour and business rules per functional block as the basis for stories and technical design.',
  inputs:['Epic (scope and KPIs)','Technical input from Tech Lead','User persona'],
  outputs:['Functional description of behaviour','Business rules','Basis for user stories'],
  flow:[
    {name:'Epic Approved',sub:'Trigger',type:'trigger'},
    {name:'Feature Draft',sub:'Business Analyst',type:'step'},
    {name:'Tech Review',sub:'Tech Lead feasibility',type:'step'},
    {name:'Sign-off PO',sub:'Functional agreement',type:'signoff'},
    {name:'Stories Start',sub:'Feature is living doc',type:'output'},
  ],
  note:'',
  refs:[{dir:'→',key:'api'},{dir:'→',key:'adr'}],
  creation:[
    {name:'Feature decomposition session',method:'Three Amigos (BA + TL + Tester)',tools:'Miro, video call',ai:false},
    {name:'Define business rules',method:'State machine analysis',tools:'Miro, draw.io',ai:true},
    {name:'Write feature doc',method:'Structured writing',tools:'Claude, Markdown',ai:true},
    {name:'Tech review',method:'Feasibility review',tools:'GitHub, Confluence',ai:false},
  ],
  template:'# Feature: [Name]\n\nEpic: [link]\n\n## Description\n\n## User Goals\n\n## Business Rules\n| # | Rule | Example |\n|---|---|---|\n\n## State Machine\n| State | Trigger | Next State | Actor |\n|---|---|---|---|\n\n## Acceptance Criteria (summary)\n\n## Out of Scope\n\n## Open Questions\n\n## Change Log\n| Date | Change | Author |\n|---|---|---|\n',
  aiTasks:[
    {name:'Business Rules Extractor',persona:'Senior Business Analyst',objective:'Surface implicit business rules assumed but not yet documented.',prompt:'You are a Senior BA. Read this feature and identify implicit business rules. Write each as: "IF [condition] THEN [result]". Flag rules that conflict with each other. Output: original assumption | explicit rule | conflict risk.'},
    {name:'Complexity Estimator',persona:'Tech Lead',objective:'Assess technical complexity and surface implementation risks.',prompt:'You are a Tech Lead. Assess this feature: (1) complexity H/M/L with justification, (2) key implementation risks, (3) architectural decisions required, (4) estimated story count. Flag anything needing clarification before stories are written.'},
  ],
},

{
  phase:'solution', key:'story',
  title:'User Story', sub:'Smallest unit of user value',
  path:'[project]/02_solution/epic-[name]/feature-[name]/stories/[story-name]/story.md',
  owner:'Business Analyst',
  reviewers:['Developer','Tester','Product Owner'],
  signoff:'Product Owner',
  lifecycle:'One-time — closed after sprint review',
  trigger:'Feature approved — refinement session planned',
  doel:'Define one testable piece of user value. Acceptance criteria live in a separate ac.md file.',
  inputs:['Feature (scope and business rules)','User persona','Technical constraints from developer'],
  outputs:['Story definition','Linked to ac.md for acceptance criteria','Ready for sprint after refinement'],
  flow:[
    {name:'Refinement',sub:'BA + Dev + Tester',type:'trigger'},
    {name:'Story Draft',sub:'BA writes story',type:'step'},
    {name:'AC Written',sub:'BA writes ac.md (separate)',type:'step'},
    {name:'Sign-off PO',sub:'"Ready for sprint"',type:'signoff'},
    {name:'In Sprint',sub:'Closed after DoD',type:'output'},
  ],
  note:'Acceptance Criteria are maintained in a separate ac.md file alongside story.md. This improves AI processing and keeps each file focused.',
  refs:[{dir:'←',key:'feature'},{dir:'→',key:'ac'}],
  creation:[
    {name:'Refinement session',method:'Three Amigos',tools:'Jira, video call, Miro',ai:false},
    {name:'Write story in INVEST format',method:'User story template',tools:'Jira, Claude',ai:true},
    {name:'Define ACs (in ac.md)',method:'EARS notation',tools:'Claude, Markdown',ai:true},
    {name:'Estimate',method:'Planning Poker / T-shirt sizing',tools:'Scrum poker app, Jira',ai:false},
  ],
  template:'# User Story: [Name]\n\n**As a** [role],\n**I want to** [action],\n**so that** [value].\n\nFeature: [link]\nStatus: draft / in review / approved / in sprint / done\nPoints: ?\n\n## Out of Scope\n\n## Notes\n\n## Linked Documents\n- Acceptance Criteria: ac.md\n- NFR: nfr.md (if applicable)\n',
  aiTasks:[
    {name:'INVEST Validator',persona:'Agile Coach',objective:'Validate the story meets INVEST criteria (Independent, Negotiable, Valuable, Estimable, Small, Testable).',prompt:'You are an Agile Coach. Validate this user story against INVEST: (1) Independent — can it be delivered without other stories? (2) Negotiable — is the scope flexible? (3) Valuable — clear user value? (4) Estimable — enough detail to estimate? (5) Small — fits in one sprint? (6) Testable — can it be verified? Output PASS/WARN/FAIL per criterion.'},
    {name:'Story Splitter',persona:'Senior Business Analyst',objective:'Split the story into smaller sub-stories if it is too large for a single sprint.',prompt:'You are a Senior BA. Assess if this user story is too large for one sprint. If yes, suggest 2-3 smaller sub-stories using valid splitting patterns (by workflow step, business rule, user role, data type, CRUD operation, happy path first). Each sub-story must be independently deliverable.'},
  ],
},

{
  phase:'solution', key:'ac',
  title:'Acceptance Criteria', sub:'EARS-format criteria per user story',
  path:'[project]/02_solution/epic-[name]/feature-[name]/stories/[story-name]/ac.md',
  owner:'Business Analyst',
  reviewers:['QA Engineer','Product Owner'],
  signoff:'Product Owner',
  lifecycle:'One-time — closed with the story after sprint review',
  trigger:'User story drafted in story.md',
  doel:'Define all testable conditions for accepting a story as done, separated from the story definition for clarity and AI processing efficiency.',
  inputs:['User story (story.md)','Feature (business rules)','Technical constraints from developer'],
  outputs:['Verifiable acceptance criteria in EARS format','Input for QA test cases','Edge case coverage'],
  flow:[
    {name:'Story Drafted',sub:'story.md written',type:'trigger'},
    {name:'Write ACs',sub:'BA — EARS notation',type:'step'},
    {name:'Edge Case Review',sub:'QA Engineer adds cases',type:'step'},
    {name:'Sign-off PO',sub:'Criteria approved',type:'signoff'},
    {name:'Linked to Story',sub:'Closed with story',type:'output'},
  ],
  note:'EARS notation: WHEN [condition] THE [actor] SHALL [observable behaviour]. Keep each AC independently verifiable.',
  refs:[{dir:'←',key:'story'},{dir:'←',key:'feature'}],
  creation:[
    {name:'Read feature and story',method:'Requirements analysis',tools:'Markdown, Claude',ai:true},
    {name:'Write happy path ACs',method:'EARS notation',tools:'Claude, Markdown',ai:true},
    {name:'Add edge cases and error scenarios',method:'Boundary analysis, equivalence partitioning',tools:'Claude, spreadsheet',ai:true},
    {name:'QA review and tester walkthrough',method:'Review session',tools:'Video call, GitHub PR',ai:false},
  ],
  template:'# Acceptance Criteria: [Story Name]\n\nStory: [link to story.md]\nFeature: [link]\nStatus: draft / approved\n\n## Happy Path\n\n### AC-1: [Short name]\nWHEN [condition]\nTHE [actor] SHALL [observable behaviour]\n\n## Edge Cases\n\n### AC-2: [Short name]\nWHEN [condition]\nTHE [actor] SHALL [observable behaviour]\n\n## Error Scenarios\n\n### AC-3: [Short name]\nWHEN [condition]\nTHE [actor] SHALL [observable behaviour]\n\n## Notes\n',
  aiTasks:[
    {name:'AC Generator',persona:'QA Engineer',objective:'Generate complete EARS-format ACs covering happy path, edge cases, and error scenarios.',prompt:'You are a QA Engineer expert in EARS notation (WHEN [condition] THE [actor] SHALL [observable behaviour]). Based on this story and feature, generate: (1) happy path ACs, (2) edge case ACs (boundaries, empty states, max values), (3) error scenario ACs (invalid input, auth failures, system errors). Each AC must be independently testable.'},
    {name:'Edge Case Detective',persona:'Security Engineer',objective:'Identify security, permission, and boundary edge cases the BA likely missed.',prompt:'You are a Security Engineer reviewing requirements. Identify: (1) authorisation edge cases (unauthorised data access), (2) input validation gaps (injection, XSS, oversized input), (3) concurrency issues (race conditions, simultaneous submits), (4) state edge cases (unexpected object states). Output as "What if..." scenarios, each a candidate AC.'},
  ],
},

// ══ DELIVERY ══════════════════════════════════════════════════════════════

{
  phase:'delivery', key:'dod',
  title:'Definition of Done', sub:'When is a story truly complete',
  path:'[project]/03_delivery/definition-of-done.md',
  owner:'Tech Lead',
  reviewers:['Full Team'],
  signoff:'Full Team',
  lifecycle:'Living — reviewed every 3 sprints or at retrospectives',
  trigger:'Team start or retrospective',
  doel:'Create shared understanding of "done" so stories are consistently and completely delivered.',
  inputs:['Team quality agreements','Lessons from previous sprints'],
  outputs:['Checklist every story must pass'],
  flow:[
    {name:'Team Start / Retro',sub:'Trigger',type:'trigger'},
    {name:'Workshop',sub:'Full team',type:'step'},
    {name:'Team Consensus',sub:'Vote or discuss',type:'signoff'},
    {name:'Living Doc',sub:'Reviewed every 3 sprints',type:'output'},
  ],
  note:'',
  refs:[],
  creation:[
    {name:'Gather team input',method:'Retrospective or dedicated workshop',tools:'Miro, Mentimeter',ai:false},
    {name:'Review against industry standards',method:'Benchmark against DORA, ISTQB',tools:'Claude, research',ai:true},
    {name:'Draft checklist',method:'Binary criteria writing',tools:'Claude, Confluence',ai:true},
    {name:'Team consensus',method:'Vote / review',tools:'Slack poll, Jira',ai:false},
  ],
  template:'# Definition of Done\n\nVersion: [date] | From sprint: [N]\n\n## Code\n- [ ] Code reviewed by ≥1 peer\n- [ ] No new linting errors\n- [ ] Unit tests written and passing\n- [ ] No TODO/FIXME in code\n\n## Functionality\n- [ ] All ACs verified by tester\n- [ ] Happy path and edge cases tested\n- [ ] Tested in staging\n\n## Non-Functional\n- [ ] Response time within NFR targets\n- [ ] No new security vulnerabilities\n- [ ] Logging added for key operations\n\n## Documentation\n- [ ] API contract updated if changed\n- [ ] ADR written if architectural decision made\n- [ ] Release notes entry added\n\n## Process\n- [ ] PO has accepted the story\n- [ ] Story moved to Done in backlog tool\n',
  aiTasks:[
    {name:'DoD Reviewer',persona:'Agile Coach',objective:'Review DoD against industry standards and flag vague or unverifiable items.',prompt:'You are an Agile Coach. Review this DoD: (1) Are items objectively binary (pass/fail)? (2) Are categories missing (security, observability, documentation)? (3) Are items too broad? Suggest a revised DoD with specific, verifiable criteria.'},
  ],
},

{
  phase:'delivery', key:'sprint',
  title:'Sprint Plan', sub:'What we build this sprint',
  path:'[project]/03_delivery/sprint-[N]-plan.md',
  owner:'Product Owner',
  reviewers:['Tech Lead','Scrum Master'],
  signoff:'',
  lifecycle:'Per sprint — new file each sprint',
  trigger:'Start of each sprint',
  doel:'Document team commitment for this sprint based on capacity and priorities.',
  inputs:['Prioritised backlog','Team velocity','Team availability'],
  outputs:['Sprint backlog with committed stories','Sprint goal'],
  flow:[
    {name:'Sprint Start',sub:'Every 2 weeks',type:'trigger'},
    {name:'Backlog Review',sub:'PO + team',type:'step'},
    {name:'Commitment',sub:'Team sets capacity',type:'step'},
    {name:'Sprint Backlog',sub:'Sprint goal defined',type:'output'},
  ],
  note:'',
  refs:[],
  creation:[
    {name:'Backlog refinement',method:'Story review with team',tools:'Jira, Planning Poker',ai:false},
    {name:'Capacity planning',method:'Team availability check',tools:'Calendar, spreadsheet',ai:false},
    {name:'Sprint planning ceremony',method:'Scrum sprint planning',tools:'Jira, Scrum Poker, Zoom',ai:false},
    {name:'Document sprint goal',method:'Collaborative writing',tools:'Confluence, Claude',ai:true},
  ],
  template:'# Sprint [N] Plan\n\n**Sprint Goal:**\n\n**Dates:** [start] – [end]\n**Team Capacity:** [SP]\n**Velocity (prev):** [SP]\n\n## Committed Stories\n| Story | Points | Feature | Assigned | Risk |\n|---|---|---|---|---|\n\n## Risks & Dependencies\n\n## Out-of-sprint items to watch\n',
  aiTasks:[
    {name:'Risk Flagger',persona:'Scrum Master',objective:'Identify stories with unresolved dependencies or vague ACs that risk non-completion.',prompt:'You are a Scrum Master. For each committed story, flag: (1) ACs not approved, (2) unresolved tech dependencies, (3) stakeholder unavailability, (4) underestimated complexity. Output: Story | Risk | Action.'},
  ],
},

{
  phase:'delivery', key:'release',
  title:'Release Notes', sub:'What is available in production',
  path:'[project]/03_delivery/release-notes.md',
  owner:'Tech Lead',
  reviewers:['Product Owner'],
  signoff:'Product Owner',
  lifecycle:'Per release — kept cumulatively',
  trigger:'Deployment to production approved',
  doel:'Inform stakeholders of what has been delivered and serve as a reference for support.',
  inputs:['Closed stories from the release','Known limitations'],
  outputs:['Communication to stakeholders','Reference for support team'],
  flow:[
    {name:'Deploy Approved',sub:'PO + Tech Lead',type:'trigger'},
    {name:'Changelog',sub:'TL collects closed stories',type:'step'},
    {name:'PO Review',sub:'Language and completeness',type:'step'},
    {name:'Published',sub:'Sent to stakeholders',type:'output'},
  ],
  note:'',
  refs:[],
  creation:[
    {name:'Collect closed stories',method:'Jira query / git log',tools:'Jira, GitHub, Claude',ai:true},
    {name:'Write plain-language summary',method:'Stakeholder-focused rewriting',tools:'Claude',ai:true},
    {name:'PO review',method:'Content review',tools:'Confluence, Slack',ai:false},
    {name:'Publish and distribute',method:'Email / Confluence publish',tools:'Confluence, email',ai:false},
  ],
  template:'# Release Notes — v[X.Y.Z]\n\n**Date:** [date]\n**Deployed by:** [name]\n\n## What\'s New\n- [Feature]: short plain-language description\n\n## Improvements\n\n## Bug Fixes\n\n## Known Issues\n| Issue | Workaround | Planned fix |\n|---|---|---|\n\n## Out of Scope (next release)\n',
  aiTasks:[
    {name:'Stakeholder Summary Writer',persona:'Business Analyst',objective:'Rewrite technical release notes in plain language for non-technical stakeholders.',prompt:'You are a BA skilled in stakeholder communication. Rewrite these release notes in plain, non-technical language. Focus on: what the user can do now, how it improves their experience, known limitations. Max 3 sentences per feature. No jargon.'},
  ],
},

// ══ GOVERNANCE ════════════════════════════════════════════════════════════

{
  phase:'governance', key:'adr',
  title:'ADR', sub:'Architecture Decision Record',
  path:'[project]/04_governance/ADR-[N]-[title].md',
  owner:'Tech Lead',
  reviewers:['Tech Lead','Product Owner','Developer'],
  signoff:'Tech Lead',
  lifecycle:'Permanent — never deleted, only "superseded"',
  trigger:'A non-trivial decision is made that is hard to reverse',
  doel:'Permanently document architectural and business decisions with context so future teams understand why something was built a certain way.',
  inputs:['Technical or business decision','Alternatives considered','Context at time of decision'],
  outputs:['Documented decision with context','Reference for future discussions'],
  flow:[
    {name:'Decision Needed',sub:'In sprint or refinement',type:'trigger'},
    {name:'Draft ADR',sub:'Initiator writes',type:'step'},
    {name:'Review',sub:'Tech Lead + PO',type:'step'},
    {name:'Accepted',sub:'Status → Accepted',type:'signoff'},
    {name:'Permanent Archive',sub:'Never deleted',type:'output'},
  ],
  note:'An ADR is never deleted. When a decision is revised, the old ADR gets status "Superseded" and links to the new one.',
  refs:[{dir:'←',key:'story'},{dir:'←',key:'domain'}],
  creation:[
    {name:'Identify the decision need',method:'Discussion in refinement or sprint',tools:'Slack, meeting',ai:false},
    {name:'Research alternatives',method:'Literature review, POCs, Claude analysis',tools:'Claude, docs, Postman',ai:true},
    {name:'Write ADR',method:'Structured ADR template',tools:'Claude, Markdown',ai:true},
    {name:'Team review',method:'PR review or async review',tools:'GitHub PR, Confluence',ai:false},
  ],
  template:'# ADR-[N]: [Decision Title]\n\n**Status:** Proposed / Accepted / Superseded\n**Date:** [date]\n**Deciders:** [names]\n**Superseded by:** (if applicable)\n\n## Context\n\n## Decision\n\n## Alternatives Considered\n| Option | Pro | Con | Why not chosen |\n|---|---|---|---|\n\n## Consequences\n### Positive\n\n### Negative\n\n### Risks\n\n## Related ADRs\n',
  aiTasks:[
    {name:'Alternative Generator',persona:'Solution Architect',objective:'Generate alternatives not yet considered before the decision is finalised.',prompt:'You are a Solution Architect. Based on this ADR context, generate 2-3 alternatives not listed. For each: name, description, advantages, disadvantages, when it would be preferred. Goal: ensure a well-informed decision, not to undermine the chosen option.'},
    {name:'Risk Evaluator',persona:'Risk Analyst',objective:'Identify long-term risks and side effects of the chosen decision.',prompt:'You are a Risk Analyst. For the decision in this ADR, identify: (1) short-term risks (6 months), (2) long-term risks (1-3 years), (3) dependency constraints, (4) reversibility assessment. Output a risk register with probability H/M/L and impact H/M/L.'},
  ],
},

{
  phase:'governance', key:'risk',
  title:'Risk Register', sub:'Identified risks and mitigations',
  path:'[project]/04_governance/risk-register.md',
  owner:'Business Analyst',
  reviewers:['Product Owner','Tech Lead'],
  signoff:'',
  lifecycle:'Living — updated at each sprint review',
  trigger:'Project start or new risk identified',
  doel:'Keep risks visible and actionable so the team can intervene before they materialise.',
  inputs:['Team experiences','External dependencies','Stakeholder feedback'],
  outputs:['Prioritised risk list with mitigations','Input for sprint planning'],
  flow:[
    {name:'Risk Identified',sub:'By anyone',type:'trigger'},
    {name:'Add to Register',sub:'BA processes',type:'step'},
    {name:'Review',sub:'Sprint review or ad hoc',type:'step'},
    {name:'Living Doc',sub:'Continuously updated',type:'output'},
  ],
  note:'',
  refs:[],
  creation:[
    {name:'Risk brainstorm',method:'RAID log workshop',tools:'Miro, Jira',ai:false},
    {name:'Score probability/impact',method:'Risk matrix',tools:'Spreadsheet, Claude',ai:true},
    {name:'Define mitigations',method:'Structured analysis',tools:'Claude, Confluence',ai:true},
    {name:'Sprint review check',method:'Standing agenda item',tools:'Jira, meeting',ai:false},
  ],
  template:'# Risk Register\n\nLast updated: [date]\n\n## Active Risks\n| ID | Risk | Probability | Impact | Score | Mitigation | Owner | Status |\n|---|---|---|---|---|---|---|---|\n| R-1 | | H/M/L | H/M/L | | | | Open |\n\n## Closed Risks\n| ID | Risk | Closed | Outcome |\n|---|---|---|---|\n',
  aiTasks:[
    {name:'Risk Scorer',persona:'Risk Manager',objective:'Score risks and flag insufficient mitigation plans.',prompt:'You are a Risk Manager. For each risk: (1) Is the probability rating justified? (2) Is impact justified? (3) Is mitigation specific and actionable (not just "monitor")? (4) Clear owner? Flag risks needing better mitigation with concrete suggestions.'},
  ],
},

{
  phase:'governance', key:'glossary',
  title:'Glossary', sub:'Shared vocabulary for the team',
  path:'[project]/04_governance/glossary.md',
  owner:'Business Analyst',
  reviewers:['Full Team'],
  signoff:'',
  lifecycle:'Living — anyone can add terms',
  trigger:'Ambiguity about a term in a meeting or document',
  doel:'Prevent miscommunication by defining domain terms unambiguously for the whole team.',
  inputs:['Terms from meetings and documents','Domain knowledge from stakeholders'],
  outputs:['Shared term definitions','Less miscommunication in refinements'],
  flow:[
    {name:'Unclear Term',sub:'In meeting or doc',type:'trigger'},
    {name:'Define',sub:'BA + domain expert',type:'step'},
    {name:'Add to Glossary',sub:'BA processes',type:'step'},
    {name:'Living Doc',sub:'Anyone can contribute',type:'output'},
  ],
  note:'',
  refs:[],
  creation:[
    {name:'Term extraction from documents',method:'NLP / keyword analysis',tools:'Claude, Ctrl+F',ai:true},
    {name:'Validation with domain expert',method:'Interview / review',tools:'Video call, email',ai:false},
    {name:'Write definitions',method:'Plain-language writing',tools:'Claude, Confluence',ai:true},
    {name:'Team review',method:'Async review',tools:'Confluence comments',ai:false},
  ],
  template:'# Glossary\n\nLast updated: [date]\n\n## Terms\n\n### [Term]\n- **Definition:**\n- **Used in:** [documents]\n- **Synonyms:**\n- **Not to be confused with:**\n- **Example:**\n\n',
  aiTasks:[
    {name:'Term Extractor',persona:'Business Analyst',objective:'Extract domain terms from project documents that need glossary definitions.',prompt:'You are a BA reviewing project docs. Identify: (1) domain-specific terms that mean different things to tech vs. business, (2) abbreviations without definition, (3) inconsistently used terms. For each, suggest a draft definition. Output: Term | Draft Definition | Source.'},
  ],
},

// ══ ARCHITECTURE ══════════════════════════════════════════════════════════

{
  phase:'architecture', key:'api',
  title:'API Contract', sub:'Interface for consumers',
  path:'[project]/05_architecture/api/[service]-contract.md',
  owner:'Tech Lead',
  reviewers:['Developer','Business Analyst'],
  signoff:'Tech Lead',
  lifecycle:'Living — versioned on every breaking change',
  trigger:'Feature approved and technical design started',
  doel:'Define a formal contract between producers and consumers so teams work in parallel without integration surprises.',
  inputs:['Feature (behaviour)','Domain model','NFR (performance, auth)'],
  outputs:['Formal API contract','Input for code generation (openapi.yaml)'],
  flow:[
    {name:'Feature Approved',sub:'Trigger',type:'trigger'},
    {name:'API Design',sub:'Tech Lead + Backend Dev',type:'step'},
    {name:'Consumer Review',sub:'Frontend + BA check',type:'step'},
    {name:'Sign-off TL',sub:'Contract frozen',type:'signoff'},
    {name:'Versioned + Living',sub:'Breaking changes → new version',type:'output'},
  ],
  note:'Breaking changes require a new version (v2). Backward-compatible changes do not.',
  refs:[{dir:'←',key:'feature'},{dir:'←',key:'domain'}],
  creation:[
    {name:'Analyse feature requirements',method:'Feature review with BA',tools:'Confluence, Miro',ai:true},
    {name:'Design API endpoints',method:'RESTful API design',tools:'Stoplight, Postman, Claude',ai:true},
    {name:'Define error codes and auth',method:'Security review',tools:'Claude, OWASP docs',ai:true},
    {name:'Consumer review',method:'Walkthrough with frontend dev',tools:'Stoplight, GitHub PR',ai:false},
  ],
  template:'# API Contract: [Service Name]\n\nVersion: v[N] | Status: Draft / Approved\nBase URL: `/api/v[N]/`\n\n## Authentication\n- Method: Bearer JWT / API key / None\n\n## Endpoints\n\n### POST /[resource]\n\n**Purpose:**\n**Auth required:** Yes / No\n\n**Request Body**\n```json\n{\n  "field": "type | required"\n}\n```\n\n**Response 200**\n```json\n{\n  "field": "value"\n}\n```\n\n**Errors**\n| Status | Code | Description |\n|---|---|---|\n| 400 | VALIDATION_ERROR | |\n| 401 | UNAUTHORIZED | |\n| 404 | NOT_FOUND | |\n\n## Changelog\n| Version | Date | Change |\n|---|---|---|\n',
  aiTasks:[
    {name:'Contract Completeness Reviewer',persona:'Senior Backend Developer',objective:'Review the API contract for missing error cases and naming inconsistencies.',prompt:'You are a Senior Backend Developer. Review this contract: (1) missing HTTP status codes, (2) incomplete auth spec, (3) missing pagination on lists, (4) naming inconsistencies, (5) missing required fields, (6) unmarked breaking changes. Output a prioritised issue list.'},
    {name:'Security Auditor',persona:'Security Engineer',objective:'Identify authentication, authorisation, and input validation gaps.',prompt:'You are a Security Engineer (OWASP API Security Top 10). Check: (1) missing auth on sensitive endpoints, (2) over-permissive endpoints, (3) missing input validation, (4) IDOR risk, (5) missing rate limiting. Output findings by severity (critical/high/medium/low).'},
  ],
},

{
  phase:'architecture', key:'domain',
  title:'Domain Model', sub:'Entities, enums, and business rules',
  path:'[project]/05_architecture/domain/[domain]-model.md',
  owner:'Tech Lead',
  reviewers:['Business Analyst','Developer'],
  signoff:'Tech Lead',
  lifecycle:'Living — updated on domain changes',
  trigger:'Epic or feature introduces new entities or rules',
  doel:'Provide one shared domain model so backend, frontend, and specs all speak the same language.',
  inputs:['Epic (business outcome)','Feature (business rules)','ADRs for technical constraints'],
  outputs:['Shared domain model','Input for database schema','Basis for API contract'],
  flow:[
    {name:'Feature Describes Rule',sub:'Trigger',type:'trigger'},
    {name:'Model Design',sub:'Tech Lead + BA',type:'step'},
    {name:'Review',sub:'Developer + BA',type:'step'},
    {name:'Sign-off TL',sub:'Model frozen',type:'signoff'},
    {name:'Living Doc',sub:'Updated on domain changes',type:'output'},
  ],
  note:'',
  refs:[{dir:'←',key:'epic'},{dir:'→',key:'adr'}],
  creation:[
    {name:'EventStorming workshop',method:'EventStorming',tools:'Miro, sticky notes (online)',ai:false},
    {name:'Entity extraction',method:'DDD entity analysis',tools:'Miro, Claude',ai:true},
    {name:'Define relationships',method:'ER diagram',tools:'draw.io, dbdiagram.io, Claude',ai:true},
    {name:'Validate with BA',method:'Domain walkthrough',tools:'Miro, video call',ai:false},
  ],
  template:'# Domain Model: [Domain Name]\n\n## Entities\n\n### [EntityName]\n| Field | Type | Required | Constraints | Description |\n|---|---|---|---|---|\n| id | UUID | Yes | unique | |\n\n## Enums\n\n### [EnumName]\n| Value | Label | Description |\n|---|---|---|\n\n## Business Rules\n1. IF [condition] THEN [result]\n\n## Relationships\n```\n[EntityA] 1──* [EntityB]  (description)\n```\n\n## Changelog\n| Date | Change | Author |\n|---|---|---|\n',
  aiTasks:[
    {name:'DDD Entity Validator',persona:'DDD Expert',objective:'Validate the domain model against DDD principles.',prompt:'You are a DDD expert. Review this model: (1) Rich vs. anemic entities? (2) Aggregate boundaries correct? (3) Value objects used where appropriate? (4) Domain events identified? (5) Ubiquitous language consistent? Suggest concrete improvements.'},
    {name:'Database Schema Advisor',persona:'Database Architect',objective:'Translate the domain model into a database schema.',prompt:'You are a Database Architect. Based on this domain model, suggest: (1) schema with keys and constraints, (2) recommended indexes, (3) normalisation issues, (4) JSON/JSONB candidates. Format as CREATE TABLE statements with comments.'},
  ],
},

{
  phase:'architecture', key:'integration',
  title:'Integration Spec', sub:'Connection to external systems',
  path:'[project]/05_architecture/integrations/[system]-integration.md',
  owner:'Tech Lead',
  reviewers:['Developer','Business Analyst'],
  signoff:'Tech Lead',
  lifecycle:'Living — updated on external API changes',
  trigger:'Feature requires an external integration',
  doel:'Document external system integrations including error handling so developers are not dependent on tribal knowledge.',
  inputs:['Feature (behaviour)','External API documentation','ADR (partner choice)'],
  outputs:['Technical integration description','Retry logic and fallback strategy'],
  flow:[
    {name:'Integration Needed',sub:'From feature',type:'trigger'},
    {name:'Analyse External API',sub:'Tech Lead',type:'step'},
    {name:'Write Integration Doc',sub:'TL writes',type:'step'},
    {name:'Review + Sign-off',sub:'TL + developer',type:'signoff'},
    {name:'Living Doc',sub:'Updated on API changes',type:'output'},
  ],
  note:'',
  refs:[{dir:'←',key:'adr'},{dir:'←',key:'feature'}],
  creation:[
    {name:'Analyse external API',method:'API documentation review',tools:'Postman, Stoplight, Claude',ai:true},
    {name:'Design integration flow',method:'Sequence diagram',tools:'Miro, draw.io, PlantUML',ai:true},
    {name:'Define error handling',method:'Error code analysis',tools:'Claude, spreadsheet',ai:true},
    {name:'Developer review',method:'Code walkthrough',tools:'GitHub PR, video call',ai:false},
  ],
  template:'# Integration Spec: [External System]\n\n## Purpose\n\n## External System\n- **Provider:**\n- **API Version:**\n- **Auth Method:**\n- **Docs URL:**\n- **Sandbox URL:**\n\n## Integration Points\n\n### [Endpoint / Trigger]\n**Direction:** Inbound / Outbound\n**When:**\n\n**Request**\n```json\n{}\n```\n\n**Response**\n```json\n{}\n```\n\n## Error Handling\n| Error | Code | Retry? | Max | Backoff | Fallback |\n|---|---|---|---|---|---|\n\n## Monitoring\n\n## Changelog\n',
  aiTasks:[
    {name:'Error Handling Advisor',persona:'Senior Backend Developer',objective:'Review error handling and retry logic for completeness.',prompt:'You are a Senior Backend Dev experienced in distributed systems. Review this integration: (1) All error codes handled? (2) Retry strategy appropriate (exponential backoff, circuit breaker)? (3) Dead letter queue / fallback for unrecoverable failures? (4) Idempotent? (5) Behaviour during outage? Suggest concrete improvements.'},
  ],
},

{
  phase:'architecture', key:'nfr',
  title:'Non-Functional Requirements', sub:'Performance, availability, observability',
  path:'[project]/05_architecture/nfr/[domain]-nfr.md',
  owner:'Tech Lead',
  reviewers:['Product Owner','Business Analyst'],
  signoff:'Product Owner',
  lifecycle:'Living — reviewed on production issues or new SLAs',
  trigger:'Epic or feature has measurable quality requirements',
  doel:'Define measurable quality targets early in design so they are built in, not bolted on.',
  inputs:['Epic KPIs','Production data','Stakeholder expectations'],
  outputs:['Measurable performance and availability targets','Basis for load testing and monitoring'],
  flow:[
    {name:'KPI in Epic',sub:'Trigger',type:'trigger'},
    {name:'Define NFRs',sub:'Tech Lead + PO',type:'step'},
    {name:'Sign-off PO',sub:'Business value confirmed',type:'signoff'},
    {name:'Living Doc',sub:'Reviewed based on data',type:'output'},
  ],
  note:'NFRs added post-development are hard to retrofit. Define alongside the epic.',
  refs:[{dir:'←',key:'epic'}],
  creation:[
    {name:'Analyse epic KPIs',method:'KPI-to-NFR translation workshop',tools:'Spreadsheet, Claude',ai:true},
    {name:'Benchmark against production',method:'APM data analysis',tools:'Grafana, DataDog, Claude',ai:true},
    {name:'Define test strategy',method:'Load test planning',tools:'k6, Claude',ai:true},
    {name:'Sign-off with PO',method:'Review meeting',tools:'Confluence, Zoom',ai:false},
  ],
  template:'# Non-Functional Requirements: [Domain]\n\n## Performance\n| Metric | Target | Percentile | Measurement |\n|---|---|---|---|\n| Response time | < 500ms | p95 | APM |\n| Throughput | > 100 req/s | sustained | Load test |\n\n## Availability\n- **Uptime target:** 99.9%\n- **RTO:**\n- **RPO:**\n\n## Security\n- Auth requirements:\n- Encryption at rest: Yes / No\n- Encryption in transit: TLS 1.2+\n\n## Scalability\n- Expected DAU:\n- Peak multiplier:\n\n## Observability\n- Logging: structured JSON\n- Alerting: on error rate > X%\n\n## Test Strategy\n| Test Type | Tool | Pass Criteria |\n|---|---|---|\n| Load | k6 | p95 < 500ms @ 100 req/s |\n| Soak | k6 | No memory leak over 4h |\n',
  aiTasks:[
    {name:'Metric Definer',persona:'Solution Architect',objective:'Convert vague quality goals into specific, measurable NFR targets.',prompt:'You are a Solution Architect. Review these NFRs: (1) Convert vague requirements into specific targets with percentile specs (p50/p95/p99), (2) Add measurement methods per metric, (3) Suggest missing categories (GDPR, data retention), (4) Flag unrealistic targets. Output a revised NFR table.'},
    {name:'Test Strategy Advisor',persona:'Performance Engineer',objective:'Define a test strategy validating each NFR before production deployment.',prompt:'You are a Performance Engineer. Define a test strategy: (1) load test scenarios with user counts, (2) stress test thresholds, (3) soak test duration, (4) tools needed, (5) go/no-go criteria. Format as a test plan with phases: baseline, load, stress, soak.'},
  ],
},

,

{
  phase:'delivery', key:'test-plan',
  title:'Test Plan', sub:'Test scope, approach, and test cases',
  path:'[project]/03_delivery/test-plan-[feature].md',
  owner:'QA Engineer',
  reviewers:['Tech Lead','Business Analyst'],
  signoff:'Tech Lead',
  lifecycle:'Per feature or release — created before development starts on a feature',
  trigger:'Feature approved and before sprint development begins',
  doel:'Define what will be tested, how, and by whom — before development starts — so quality is built in, not checked at the end.',
  inputs:['Feature (scope and business rules)','Acceptance criteria (ac.md)','NFR (performance targets if applicable)'],
  outputs:['Test scope and out-of-scope','Test cases linked to ACs','Test environment requirements','Entry and exit criteria'],
  flow:[
    {name:'Feature Approved',sub:'Trigger',type:'trigger'},
    {name:'Write Test Plan',sub:'QA Engineer',type:'step'},
    {name:'Review with TL + BA',sub:'Completeness check',type:'step'},
    {name:'Sign-off TL',sub:'Plan approved',type:'signoff'},
    {name:'Tests Executed',sub:'During and after sprint',type:'output'},
  ],
  note:'A test plan written before development guides implementation. Writing it after development is a test report, not a test plan.',
  refs:[{dir:'←',key:'ac'},{dir:'←',key:'feature'},{dir:'←',key:'nfr'}],
  creation:[
    {name:'Analyse ACs and feature',method:'Requirements analysis',tools:'Claude, Markdown',ai:true},
    {name:'Define test scope',method:'Risk-based test scope selection',tools:'Spreadsheet, Claude',ai:true},
    {name:'Write test cases',method:'Equivalence partitioning, boundary analysis',tools:'Jira, TestRail, Claude',ai:true},
    {name:'Review with team',method:'Walkthrough session',tools:'Video call, Confluence',ai:false},
  ],
  template:'# Test Plan: [Feature Name]\n\nVersion: 1.0 | Date: [date]\nFeature: [link]\nAC: [link to ac.md]\n\n## Test Scope\n\n### In Scope\n\n### Out of Scope\n\n## Test Approach\n\n| Level | Type | Tool | Owner |\n|---|---|---|---|\n| Unit | Automated | Jest / pytest | Developer |\n| Integration | Automated | Supertest / pytest | Developer |\n| E2E | Manual + Automated | Playwright | QA |\n| Performance | Automated | k6 | QA |\n\n## Entry Criteria\n- [ ] Feature development complete\n- [ ] Unit tests passing\n- [ ] Deployed to test environment\n\n## Exit Criteria\n- [ ] All ACs verified\n- [ ] Zero open critical/high bugs\n- [ ] Performance targets met (if NFR defined)\n\n## Test Cases\n\n| ID | AC | Description | Steps | Expected Result | Pass/Fail |\n|---|---|---|---|---|---|\n| TC-1 | AC-1 | Happy path | 1. ... | ... | |\n| TC-2 | AC-2 | Edge case | 1. ... | ... | |\n\n## Test Environment\n\n- URL: \n- Test data:\n- External systems: \n\n## Risks\n\n| Risk | Mitigation |\n|---|---|\n',
  aiTasks:[
    {name:'Test Case Generator',persona:'QA Engineer',objective:'Generate comprehensive test cases from the ACs and feature description.',prompt:'You are a QA Engineer. Based on the ACs and feature description, generate test cases covering: (1) one test case per AC (happy path), (2) edge case test cases (boundaries, empty inputs, max values), (3) negative test cases (invalid input, permission denied, system errors). For each: ID, linked AC, description, steps, expected result. Format as a markdown table.'},
    {name:'Risk-Based Scope Advisor',persona:'Test Manager',objective:'Identify the highest-risk areas to focus test effort on.',prompt:'You are a Test Manager with expertise in risk-based testing. Analyse this feature and ACs. Identify: (1) highest-risk areas by probability × impact, (2) areas where automated testing adds most value, (3) areas requiring manual exploratory testing. Suggest a test priority order: critical (must test) / important (should test) / optional (nice to test).'},
  ],
},

]; // end DEFAULT_DOCUMENTS
