export const state = {
  projects: [],
  activeProject: null,
  githubRepo: null,
  tree: [],
  modifiedFiles: new Set(),
  tagFiles: new Set(),
  tagData: [],
  diffStatFiles: {},
  currentFile: null,
  originalContent: "",
  currentMdContent: "",
  inlineDiffActive: false,
  activeFilter: "all",
  searchQ: "",
};
